ALTER TABLE LOCATIONS DROP COLUMN IF EXISTS county;
ALTER TABLE LOCATIONS ADD COLUMN IF NOT EXISTS county_id int NOT NULL references counties;
ALTER TABLE LOCATIONS ADD COLUMN IF NOT EXISTS region_id int NOT NULL references regions;
ALTER TABLE LOCATIONS ADD COLUMN IF NOT EXISTS country_id int NOT NULL references countries;
ALTER TABLE LOCATIONS ADD COLUMN IF NOT EXISTS lat numeric NOT NULL;
ALTER TABLE LOCATIONS ADD COLUMN IF NOT EXISTS lon numeric NOT NULL;
