ALTER TABLE COUNTIES ADD COLUMN IF NOT EXISTS lat numeric (8, 5) NOT NULL;
ALTER TABLE COUNTIES ADD COLUMN IF NOT EXISTS lon numeric (8, 5) NOT NULL;
ALTER TABLE REGIONS ADD COLUMN IF NOT EXISTS lat numeric (8, 5) NOT NULL;
ALTER TABLE REGIONS ADD COLUMN IF NOT EXISTS lon numeric (8, 5) NOT NULL;
ALTER TABLE COUNTRIES ADD COLUMN IF NOT EXISTS lat numeric (8, 5) NOT NULL;
ALTER TABLE COUNTRIES ADD COLUMN IF NOT EXISTS lon numeric (8, 5) NOT NULL;
